In [1]:
import os
import wget
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model

In [2]:
ifile = 'homeprice_multivariate.csv'
if os.path.isfile(ifile):
    print('file exists')
else:
    wget.download('https://raw.githubusercontent.com/codebasics/py/master/ML/2_linear_reg_multivariate/homeprices.csv',ifile)

file exists


In [3]:
df = pd.read_csv(ifile)
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [4]:
import math
median_bedroom = math.floor(df['bedrooms'].median())

In [5]:
df['bedrooms'] = df['bedrooms'].fillna(median_bedroom)

In [6]:
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [7]:
lreg = linear_model.LinearRegression()

In [8]:
lreg.fit(df[['area','bedrooms','age']], df['price'])

LinearRegression()

In [9]:
print(lreg.coef_)
print(lreg.intercept_)

[  112.06244194 23388.88007794 -3231.71790863]
221323.00186540425


In [10]:
lreg.predict([[3000, 3, 40]])

array([498408.25158031])

### Exercise: Predict hiring salary

In [11]:
ex_file = 'hiring_salary.csv'
if os.path.isfile(ex_file):
    print('file exists')
else:
    wget.download('https://raw.githubusercontent.com/codebasics/py/master/ML/2_linear_reg_multivariate/Exercise/hiring.csv',ex_file)

file exists


In [12]:
df = pd.read_csv(ex_file)
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [13]:
df.rename(columns={'test_score(out of 10)':'test_score','interview_score(out of 10)':'interview_score','salary($)':'salary'}, inplace=True)

In [14]:
df

experience  test_score  interview_score  salary
0        NaN         8.0                9   50000
1        NaN         8.0                6   45000
2       five         6.0                7   60000
3        two        10.0               10   65000
4      seven         9.0                6   70000
5      three         7.0               10   62000
6        ten         NaN                7   72000
7     eleven         7.0                8   80000

In [15]:
df['test_score'] = df['test_score'].fillna(df['test_score'].median())

In [16]:
df['experience'] = df['experience'].fillna('zero')

In [17]:
df

experience  test_score  interview_score  salary
0       zero         8.0                9   50000
1       zero         8.0                6   45000
2       five         6.0                7   60000
3        two        10.0               10   65000
4      seven         9.0                6   70000
5      three         7.0               10   62000
6        ten         8.0                7   72000
7     eleven         7.0                8   80000

In [18]:
from word2number import w2n

In [19]:
df['experience'] = df['experience'].apply(w2n.word_to_num)

In [20]:
df

experience  test_score  interview_score  salary
0           0         8.0                9   50000
1           0         8.0                6   45000
2           5         6.0                7   60000
3           2        10.0               10   65000
4           7         9.0                6   70000
5           3         7.0               10   62000
6          10         8.0                7   72000
7          11         7.0                8   80000

In [21]:
lreg = linear_model.LinearRegression()

In [22]:
lreg.fit(df[['experience','test_score','interview_score']], df['salary'])

LinearRegression()

In [23]:
print(lreg.coef_)
print(lreg.intercept_)

[2812.95487627 1845.70596798 2205.24017467]
17737.26346433768


In [26]:
lreg.predict([[2, 9, 6],[12, 10, 10]])

array([53205.96797671, 92002.18340611])